### ISSUE TITLE
豆豆哥，你的网站好像被DDOS了 。。

### ISSUE THREAD

**Issue by leo2n** [ToyoDAdoubi/doubi#10]
貌似ramnode也被连累了，Atlanta的机房，也就是bid的域名也打不开了。

**Comment by ToyoDAdoubi** [comment]
@leo2n 是我网站被CC了，攻击者 sstest.cc

**Comment by leo2n** [comment]
那怎么办呢？cc攻击如果换ip攻击的话不好弄，我刚看到你把网站转移到cloudfare上了，不过还是redireced too many times，不能访问。

**Comment by tiexo** [comment]
上不去了...

**Comment by Sharkkkk** [comment]
网站关闭了？
