### ISSUE TITLE
pac_get.sh输出地址能不能灵活机动点

### ISSUE THREAD

**Issue by Ecareyu** [ToyoDAdoubi/doubi#12]
大佬你输出的地址是你服务器上的，我服务器上没有这个路径，直接gg了，然后我改成了./输出当当前目录临时解决了，能不能改一下这个输出路径。

**Comment by ToyoDAdoubi** [comment]
因为我本来就是自用的呀，公开这个脚本只是让需要的人去使用或者是研究转换方法，自己使用时，改一下输出路径就行了。
