### ISSUE TITLE
Anyconnect脚本的try-mtu-discovery

### ISSUE THREAD

**Issue by g708659** [ToyoDAdoubi/doubi#14]
Toyo君好

首先，感谢你的脚本们，使得梯子部署更快捷。
只是有一个小小的细节可改进之处请你海涵：
Anyconnect脚本，conf文件的try-mtu-discovery项强烈建议默认改为false（除非有其它更严重的安全考虑），不然很多客户端在WiFi环境下默认1500的MTU去连该脚本自架的ocserv的会强行被设1000的MTU，然后被断开（连接重置）。

表示踩了这个坑观察了几个小时才发现这个问题,希望能在你的新版脚本中成为一个默认的优化。

**Comment by ToyoDAdoubi** [comment]
不清楚，不过我已经更新了 配置文件(和脚本是分开的)，我把这个参数注释了。
