### ISSUE TITLE
srr.sh 中 libsodium的下载地址不对

### ISSUE THREAD

**Issue by Chao-zhi** [ToyoDAdoubi/doubi#15]
如题

**Comment by snchrome** [comment]
自己手动修改就好了。
` Check_Libsodium_ver
        if [[ ${release} == "centos" ]]; then
                yum update
                echo -e "${Info} 安装依赖..."
                yum -y groupinstall "Development Tools"
                echo -e "${Info} 下载..."
                wget  --no-check-certificate -N "https://github.com/jedisct1/libsodium/archive/${Libsodiumr_ver}-RELEASE.tar.gz"
                echo -e "${Info} 解压..."
                tar -xzf ${Libsodiumr_ver}-RELEASE.tar.gz && cd libsodium-${Libsodiumr_ver}-RELEASE
                echo -e "${Info} 编译安装..."
                ./configure --disable-maintainer-mode && make -j2 && make install
                echo /usr/local/lib > /etc/ld.so.conf.d/usr_local_lib.conf
        else
                apt-get update
                echo -e "${Info} 安装依赖..."
                apt-get install -y build-essential
                echo -e "${Info} 下载..."
                wget  --no-check-certificate -N "https://github.com/jedisct1/libsodium/archive/${Libsodiumr_ver}-RELEASE.tar.gz"
                echo -e "${Info} 解压..."
                tar -xzf ${Libsodiumr_ver}-RELEASE.tar.gz && cd libsodium-${Libsodiumr_ver}-RELEASE
                echo -e "${Info} 编译安装..."
                ./configure --disable-maintainer-mode && make -j2 && make install
        fi
        ldconfig
        cd .. && rm -rf ${Libsodiumr_ver}-RELEASE.tar.gz && rm -rf libsodium-${Libsodiumr_ver}-RELEASE
        [[ ! -e ${Libsodiumr_file} ]] && echo -e "${Error} libsodium 安装失败 !" && exit 1
`

**Comment by shinkamui** [comment]
主要是新版版本字符串里面有release字样，正则规则剔除了，于是url就错误了。手动改regex或是直接把版本改成上一版就好了。
