### ISSUE TITLE
大佬，在根据地留言留不上去，无奈挂到这里了，求大佬临幸一哈

### ISSUE THREAD

**Issue by win434545299** [ToyoDAdoubi/doubi#21]
逗逼大佬，有木有最新的SSR的计费网站源码啊，翻了很多帖子找不到，和几个哥们一起用一个服务器，有人老是不交钱...= =...干脆搭个计费网站算了，控制一下他们，哼哼，跪谢大佬

**Comment by nomoneynolife** [comment]
作者已坐牢，详情请见郑州人民检察院以提供入侵计算机系统工具罪对孙东洋提起公诉！

**Comment by kyarazhan** [comment]
> 作者已坐牢，详情请见郑州人民检察院以提供入侵计算机系统工具罪对孙东洋提起公诉！

逗逼的脚本是不是废了？
