### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by shellhub** [ToyoDAdoubi/doubi#22]
ss多用户脚本运行后服务器服务使用回车，会出现问号❓乱码

**Comment by ToyoDAdoubi** [comment]
我没有ss多用户脚本，我只用 ssrmu.sh SSR多用户脚本。
回车出现问号乱码？你需要提供更详细的信息，否则无法判断。

**Comment by shellhub** [comment]
我用的就是你的ssrmu.sh脚本，然后每次运行后可以正常运行，然后如果某一时刻我发现我输入错误，想按Backspace删除多余内容，发现不能正常删除，会出现?，无法正常使用Backspace

**Comment by ToyoDAdoubi** [comment]
正常情况，你使用的多半不是Xshell SSH工具，不同SSH工具出现的情况不一样，因为只能屏蔽一个，所以我屏蔽了 Xshell 退格键弹出的 ^H ，其他的SSH工具请通过 Shift+退格键 或 Ctrl+退格键（取决于SSH工具的按键设置） 去删除字符。

**Comment by shellhub** [comment]
谢谢你的解答，你说的这些屏蔽方法都不适合，我用的是mac os自带SSH,我在想是不是因为你的脚本是中文的缘故,因为不运行脚本的话退格键正常,用了就不正常了，退出登录又正常了
