### ISSUE TITLE
请求帮助ocserv.sh连接不上。

### ISSUE THREAD

**Issue by jinweime** [ToyoDAdoubi/doubi#23]
查看日志显示的LOG
----
note: setting 'plain' as primary authentication method
note: setting 'file' as supplemental config option
listening (TCP) on 0.0.0.0:8009...
listening (UDP) on 0.0.0.0:8009...
ocserv[8954]: main: initialized ocserv 0.11.8
ocserv[8956]: sec-mod: reading supplemental config from files
ocserv[8956]: sec-mod: sec-mod initialized (socket: /var/run/ocserv-socket.8954)
----

我是用的 
wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ocserv.sh && chmod +x ocserv.sh && bash ocserv.sh   命令
在阿里云服务上搭建的这个脚本，AnyConnect就是连接不上。

**Comment by jinweime** [comment]
折腾了二天换了vultr vps试了下，成功的连接上了！
好强大的脚本  小白必备 谢谢作者

**Comment by jinweime** [comment]
国内的阿里云是不是禁用了什么？才出现的那个问题

**Comment by ToyoDAdoubi** [comment]
日志没有报错输出，你连接不上，多半是阿里云外部防火墙的问题（后台的安全组/规则组，自己找）。
