### ISSUE TITLE
error opening socket: Operation not permitted 

### ISSUE THREAD

**Issue by jinweime** [ToyoDAdoubi/doubi#24]
你好！请问这是什么原因？

ocserv[22379]: error opening socket: Operation not permitted 
ocserv[22379]: GnuTLS error (at worker-vpn.c:602): GnuTLS internal error. 
ocserv[22285]: main: 221.223.115.52:37553 user disconnected (reason: unspecified, rx: 0, tx: 0)

**Comment by luodaoyi** [comment]
权限问题 请使用sudo执行相关命令
