### ISSUE TITLE
网站打不开了

### ISSUE THREAD

**Issue by sandyplus** [ToyoDAdoubi/doubi#3]
老大，你的网站打不开了，怎么回事？

**Comment by afeigorgor** [comment]
？

sandy <notifications@github.com> 于 2018年12月7日周五 10:46写道：

**Comment by smallmj** [comment]
https://doub.io/ss-jc60/ 这个网站打不开了，域名到期了？

**Comment by xxyzuo** [comment]
站长失联了，脚本最好不要用
