### ISSUE TITLE
pac_get.sh 里面的 __PROXY__ 是什么？

### ISSUE THREAD

**Issue by passos** [ToyoDAdoubi/doubi#32]
如题，这是个什么意思？查了各种文档也没有提到。按规定不是要返回一个类似 "SOCKS 127.0.0.1:8080" 这种代理描述吗？

**Comment by ToyoDAdoubi** [comment]
SSR 使用时，会搜索这个关键词并替换为 代理服务器信息 比如 PROXY 127.0.0.1:1080 。
