### ISSUE TITLE
Cloud-torrent Not working on Raspberry Pi

### ISSUE THREAD

**Issue by jokerknight** [ToyoDAdoubi/doubi#33]
I have tried running on Raspberry Pi who was based on Debian 9..
But it's not running when run command  ``/etc/init.d/cloudt start``.
Check the log show that  ./cloud-torrent: cannot execute binary file: Exec format error 
it's look like not support ARM Cpus.

**Comment by ToyoDAdoubi** [comment]
@jokerknight 服务器上请输入 `uname -m` 告诉我显示的是什么。
