### ISSUE TITLE
如果有可能，brook的安装脚本改为英文

### ISSUE THREAD

**Issue by jy00566722** [ToyoDAdoubi/doubi#35]
感谢了。brook的安装脚本。
不过中文提示，有时候显示乱码，要折腾好久啊。
如果直接提示英文 ，可能更方便。（虽然提示中文也是为了方便)

**Comment by ToyoDAdoubi** [comment]
你用的什么 SSH工具？我用 putty xshell 都没有中文乱码，也有可能是系统问题，不过系统往往都是能显示但是不能输入中文。
另外我英语渣，就算翻译成英语也是机翻，有兴趣可以自己翻译。

**Comment by jy00566722** [comment]
感谢了，我换了putty，显示中文正常了。
