### ISSUE TITLE
ssr.sh中执行时报错了

### ISSUE THREAD

**Issue by claer-ding** [ToyoDAdoubi/doubi#39]
': 不是有效的标识符H
-bash: $'\r': 未找到命令
-bash: $'\r': 未找到命令
dirname：无效选项 -- b
Try 'dirname --help' for more information.
-bash: $'\r': 未找到命令
-bash: ssr.sh:行34: 未预期的符号 `$'{\r'' 附近有语法错误
'bash: ssr.sh:行34: `check_root(){

**Comment by ToyoDAdoubi** [comment]
已解决换行符问题。
