### ISSUE TITLE
大佬啊，Vultr最近疯狂被封IP，有啥好推荐的嘛

### ISSUE THREAD

**Issue by zhz1237ok** [ToyoDAdoubi/doubi#43]
搬瓦工最近也挂了，逗哥目前用来建网站的是哪个VPS供应商？

**Comment by ccgaryngcc** [comment]
我是香港人... 但是我回內地的時候用的還是Google Cloud Platform所設的Virtural Machine的SSR. 奇怪地IP沒有被封,而且100%IP都可用,你們試一下吧 加油加油

**Comment by ToyoDAdoubi** [comment]
建议避开美国、日本服务器，有效降低被墙几率（至少这几年我自用的服务器是这样）。
