### ISSUE TITLE
cloudt.sh无法启动，求助

### ISSUE THREAD

**Issue by 2050545641** [ToyoDAdoubi/doubi#45]
cloudt.sh安装完启动不了，log显示如下：
![ip](https://user-images.githubusercontent.com/30212669/42122437-7190b522-7c74-11e8-982c-ad61849d7e8d.png)
服务器上装了宝塔面板+lnmp，会不会跟这个有冲突？

**Comment by ToyoDAdoubi** [comment]
当你要绑定域名的时候，请先确保域名解析成功，Cloud Torrent 在启动的时候会检查域名的DNS解析是否是本机，如果是的话才会启动，否则就会报错，你可以服务器上面 ping 自己的域名，看看是否解析成功。

**Comment by 2050545641** [comment]
现在可以启动了，但是web页面进不去，一直卡在Connecting
![snipaste_2018-07-01_11-21-10](https://user-images.githubusercontent.com/30212669/42130760-f330271e-7d20-11e8-80b7-9309cfd694d6.png)
log：
![snipaste_2018-07-01_11-21-01](https://user-images.githubusercontent.com/30212669/42130761-f93ccc70-7d20-11e8-8078-821803cb14a4.png)
再麻烦帮我看一下吧QwQ

**Comment by ToyoDAdoubi** [comment]
你是以前进去过然后进不去了，还是从来没有进去过网页？
日志看起来正常，你试过挂代理吗？看看是不是网络连接的二问题。
