### ISSUE TITLE
brook脚本在centos7下会下载旧版kernel

### ISSUE THREAD

**Issue by helloyan** [ToyoDAdoubi/doubi#46]
CentOS Linux release 7.4.1708 (Core) ，核心Linux centos-512mb-sfo2-01-1516842305263-s-1vcpu-1gb-sfo2-01 4.16.0-1.el7.elrepo.x86_64 #1 SMP Sun Apr 1 20:13:35 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

执行一键脚本会下载 kernel  3.10.0-862.3.3.el7

**Comment by ToyoDAdoubi** [comment]
Brook 脚本并不会下载安装 kernel。
你说的这种情况可能是：
`yum update
yum install -y net-tools`
