### ISSUE TITLE
请问能写一个检测ssr节点运行状态的脚本么？

### ISSUE THREAD

**Issue by Ehco1996** [ToyoDAdoubi/doubi#5]
我在粗略的查了一下，貌似需要通过检测ssr的心跳包来判断
节点是否连通，
可是我不知道该如何实现这个功能
请问你有办法么？

**Comment by ToyoDAdoubi** [comment]
@Ehco1996  我写过：https://github.com/ToyoDAdoubi/doubi/blob/master/ssrstatus.sh

**Comment by Ehco1996** [comment]
@谢谢回复，
我看了下脚本，
这个貌似是通过 ssr 客户端 local.py 
建立本地连接之后再进行测试，
请问有没有什么更好的办法呢？

**Comment by ToyoDAdoubi** [comment]
@Ehco1996 暂时没有想到其他方法，因为要测试这个账号是否可用，就需要链接这个账号来模拟访问网站才能看出来，本来破娃看了我这个原理后说要做一下SSR检测账号可用性这方面的功能，结果还没搞或者还没搞完，就删除项目了。

**Comment by Ehco1996** [comment]
@ToyoDAdoubi 
谢谢大大回复，我想到一个比较笨的办法，
就是不检测代理是否正常运行，（默认配置成功之后手动测试是否正常运行，）
默认正常之后，检测节点状态就通过检测ss进程是否运行就成

用这条命令就行了就能检测到了
ps -ef | grep server.py| grep -v grep | wc -l

不过这样的确有点蠢，

其实这个功能一般用户也用不到，
主要是我最近在写 django 版的sspanel，需要在检测一下是否正常运行

项目地址在这 https://github.com/Ehco1996/django-sspanel 

了解ss还是通过您的博客，那时候还是在你的手把手的视频教程下才学会建站，
现在想想这么久过去了，我居然也能自己写点东西了，

再次感谢！
