### ISSUE TITLE
据说魔改BBR速度更加快

### ISSUE THREAD

**Issue by zhz1237ok** [ToyoDAdoubi/doubi#50]
https://lolico.moe/gotagota/compare-serverspeeder-and-bbr.html

大佬研究下？

**Comment by ToyoDAdoubi** [comment]
如果说原版 BBR 是一个尽量公平的天平，那么魔改 BBR 就是一个偏向于你的 天平，这不符合 BBR的初衷，也不会使互联网网络环境更好。
而且 魔改BBR 不一定比原版BBR更快，但是他绝对会损失浪费更多的流量 和 影响其他人。
