### ISSUE TITLE
能做个大陆白名单的pac吗

### ISSUE THREAD

**Issue by HellAction** [ToyoDAdoubi/doubi#6]
SSR上无法更新pac了,gfw白名单访问github之类没被墙的网站直连太慢,只能用全局+代理规则,但是缺点就是重启机子后,浏览器无法访问网络,需要手动恢复浏览器代理设置;

原来留在SSR里的大陆白名单pac.txt无效了
https://github.com/shadowsocks-r/breakwa11.github.io/blob/master/ssr/ss_cnip.pac
这个下载下来,改成txt也没用,不知道咱回事

**Comment by kmahyyg** [comment]
自己去看逗逼的tg频道，或者来试试我们的neko-dev/gfw_whitelist
