### ISSUE TITLE
https://doub.io 无法访问，新域名多少？

### ISSUE THREAD

**Issue by zhenfeii** [ToyoDAdoubi/doubi#7]

**Comment by fadeorfake** [comment]
同问啊. 很好的学习地.. 现在没了...

**Comment by ron159** [comment]
镜像站https://doubmirror.ml
主站不会更新了

**Comment by zaaja0984** [comment]
> 镜像站https://doubmirror.ml
> 主站不会更新了

镜像站也不在了吧 看到域名在拍卖

**Comment by ron159** [comment]
> > 镜像站https://doubmirror.ml
> > 主站不会更新了
> 
> 镜像站也不在了吧 看到域名在拍卖

我这边正常访问啊

**Comment by whxkdah** [comment]
请问怎么做镜像，我也想做个镜像站，以防现在的镜像站访问不了

**Comment by zhenfeii** [comment]
.

**Comment by zaaja0984** [comment]
> > > 镜像站https://doubmirror.ml
> > > 主站不会更新了
> > 
> > 
> > 镜像站也不在了吧 看到域名在拍卖
> 
> 我这边正常访问啊

翻墙就可以了谢谢
